config/routes.rb
Rails.application.routes.draw do
  get 'employment_terms/create'
  get 'divisions/index'
  get 'divisions/show'
  resources :positions
  resources :users do
    resources :employment_terms
  end

  root 'divisions#index'
end

app/models/employment_term.rb
class EmploymentTerm < ApplicationRecord
  validates :begin_date, presence: true
  
  belongs_to :user
  belongs_to :division
  belongs_to :position
end

app/controllers/employment_terms_controller.rb
class EmploymentTermsController < ApplicationController
  before_action :get_user
  before_action :set_employment_term, only: [:show, :edit, :update]

  # GET /employment_terms
  def index
    @employment_terms = @user.employment_terms
  end

  # GET /employment_terms/1
  def show
  end

  # GET /employment_terms/new
  def new
    @employment_term = @user.employment_terms.build
  end

  # GET /employment_terms/1/edit
  def edit
  end

  # POST /employment_terms
  def create
    @employment_term = @user.employment_terms.build(employment_term_params)

    if @employment_term.save
      redirect_to user_employment_terms_path(@user), notice: 'Employment term was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /employment_terms/1
  def update
    if @employment_term.update(employment_term_params)
      redirect_to user_employment_terms_path(@user), notice: 'Employment term was successfully updated.'
    else
      render :edit
    end
  end

  private

  def get_user
    @user = User.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_employment_term
    @employment_term = @user.employment_terms.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def employment_term_params
    params.require(:employment_term).permit(:user_id, :division_id, :position_id, :begin_date, :end_date)
  end
end

app/helpers/employment_terms_helper.rb
module EmploymentTermsHelper
end

app/views/employment_terms/_form.html.erb
<%= form_with(model: [@user, employment_term]) do |form| %>
  <% if employment_term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employment_term.errors.count, "error") %> prohibited this employment_term from being saved:</h2>

      <ul>
        <% employment_term.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :division_id %>
    <%= form.collection_select :division_id, Division.order(:name), :id, :name, {:include_blank => true} %>
  </div>

  <div class="field">
    <%= form.label :position_id %>
    <%= form.collection_select :position_id, PositionHistory.order(:name), :id, :name, {:include_blank => true} %>
  </div>

  <div class="field">
    <%= form.label :begin_date %>
    <%= form.date_field :begin_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employment_terms/edit.html.erb
<h1>Editing Employment Term</h1>

<%= render 'form', employment_term: @employment_term %>

<%= link_to 'Show', [@user, @employment_term] %> |
<%= link_to 'Back', user_employment_terms_path(@user) %>

app/views/employment_terms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employment Terms</h1>
<h2><%= "сотрудник #{@user.l_name} #{@user.f_name} #{@user.s_name}" %></h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Подразделение</th>
      <th>Должность</th>
      <th>Дата назначения</th>
      <th>Дата окончания</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employment_terms.each do |employment_term| %>
      <tr>
        <td><%= employment_term.division.name %></td>
        <td><%= employment_term.position.position_history.name %></td>
        <td><%= employment_term.begin_date %></td>
        <td><%= employment_term.end_date %></td>
        <td><%= link_to 'Show User', [@user] %></td>
        <td><%= link_to 'Edit Employment', edit_user_employment_term_path(@user, employment_term) %></td>
        <td><%= link_to 'Destroy Employment', [@user, employment_term], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employment Term', new_user_employment_term_path(@user) %>

app/views/employment_terms/new.html.erb
<h1>Новые условия труда</h1>
<h2><%= "сотрудник #{@user.l_name} #{@user.f_name} #{@user.s_name}" %></h2>

<%= render 'form', employment_term: @employment_term %>

<%= link_to 'Back', user_employment_terms_path(@user) %>

app/views/employment_terms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_employment_term_path(@user, @employment_term) %> |
<%= link_to 'Back', user_employment_terms_path(@user) %>