config/routes.rb
Rails.application.routes.draw do
  get 'employment_terms/create'
  get 'divisions/index'
  get 'divisions/show'
  resources :positions
  resources :users do
    resources :employment_terms
  end

  root 'divisions#index'
end

app/models/position.rb
class Position < ApplicationRecord
  has_one :position_history
  has_many :employment_terms

  accepts_nested_attributes_for :position_history
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:edit, :update, :destroy, :show]

  def index
    @positions = Position.all
  end

  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
    @position.build_position_history
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  def create
    @position = Position.new(position_params)

    if @position.save
      redirect_to positions_path, notice: 'Position was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /positions/1
  def update
    if @position.update(position_params)
      redirect_to positions_path, notice: 'Position was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /positions/1
  def destroy
    @position.destroy
    redirect_to positions_url, notice: 'Position was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit(:id, position_history_attributes: [:id, :name, :begin_date, :end_date])
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: position) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
        <% position.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.fields_for :position_history do |position_history_form| %>
    <div class="field">
      <%= position_history_form.label :name %>
      <%= position_history_form.text_field :name %>
    </div>

    <div class="field">
      <%= position_history_form.label :begin_date %>
      <%= position_history_form.date_field :begin_date %>
    </div>

    <div class="field">
      <%= position_history_form.label :end_date %>
      <%= position_history_form.date_field :end_date %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Positions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Должность</th>
      <th>Дата введения должности</th>
      <th>Дата ликвидации должности</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.position_history&.name %></td>
        <td><%= position.position_history&.begin_date %></td>
        <td><%= position.position_history&.end_date %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', positions_path %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position name:</strong>
  <%= @position.position_history.name %>
</p>

<p>
  <strong>Begin date:</strong>
  <%= @position.position_history.begin_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @position.position_history.end_date %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>