config/routes.rb
Rails.application.routes.draw do
  get 'employment_terms/create'
  get 'divisions/index'
  get 'divisions/show'
  resources :positions
  resources :users do
    resources :employment_terms
  end

  root 'divisions#index'
end

app/models/user.rb
class User < ApplicationRecord
  validates :l_name, :f_name, :s_name, presence: true

  has_many :employment_terms, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    if params[:begin_date] && params[:end_date]
      date_range = params[:begin_date]..params[:end_date]
      @employment_terms = @user.employment_terms.where(begin_date: date_range).or(@user.employment_terms.where(end_date: date_range))
      # @employment_terms = @user.employment_terms.where(["begin_date = ? OR end_date = ?", date_range, date_range])
      # binding.pry
      @title = 'Занимаемые должности на запрашиваемый период'
    else
      @employment_terms = [@user.employment_terms.find_by(end_date: nil)]
      @title = 'Текущие условия труда'
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

   # def find_by_dates
  #   if params[:begin_date] && params[:end_date]
  #    begin_date = params[:begin_date]
  #    end_date = params[:end_date]
  #    @sort_employment_term = @user.employment_terms.where(employment_terms: {:begin_date >= begin_date && :end_date <= end_date})
  #   redirect_to :action => 'find_results'  
  #   end
  # end

  # Entry.find(:all).where(:date => start_date..end_date).where(:time => start_time..end_time) 
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:l_name, :f_name, :s_name, :begin_date, :end_date)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :l_name %>
    <%= form.text_field :l_name %>
  </div>

  <div class="field">
    <%= form.label :f_name %>
    <%= form.text_field :f_name %>
  </div>

  <div class="field">
    <%= form.label :s_name %>
    <%= form.text_field :s_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Сотрудники</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Фамилия</th>
      <th>Имя</th>
      <th>Отчетство</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.l_name %></td>
        <td><%= user.f_name %></td>
        <td><%= user.s_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= "Сотрудник: #{@user.l_name} #{@user.f_name} #{@user.s_name}" %></h2>

<h2><%= @begin_date %></h2>
<h2><%= @end_date %></h2>

<h2><%= @title %></h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Подразделение</th>
        <th>Должность</th>
        <th>Дата приема</th>
        <th>Дата перевода / увольнения</th>
      </tr>
    </thead>

    <tbody>
      <% unless @user.employment_terms.empty? %>
        <% @employment_terms.each do |employment_term| %>
          <tr>
            <td><%= employment_term.division.name %></td>
            <td><%= employment_term.position.position_history.name %></td>
            <td><%= employment_term.begin_date %></td>
            <td><%= employment_term.end_date %></td>
          </tr>
        <% end %>
      <% else%>
         <tr>
            <td colspan="4">Cотрудник не имеет записей о назначении на должность</td>
          </tr>
      <% end %>
    </tbody>
  </table>

</br>
</br>
<p>Посмотреть позиции за период. Выберите начальную и конечную дату периода</p>

<%= form_with url: "/users/#{@user.id}", method: :get do |form| %>
  <div class="mb-3">
    <%= form.date_field :begin_date, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.date_field :end_date, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Применить фильтр", class: "btn btn-primary" %>
    <%= link_to 'Текущая позиция', user_path, class: "btn btn-primary"  %>
  </div>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Add EmploymentTerm', user_employment_terms_path(@user) %>
<%= link_to 'Back', users_path %>