config/routes.rb
Rails.application.routes.draw do
  get 'employment_terms/create'
  get 'divisions/index'
  get 'divisions/show'
  resources :positions
  resources :users do
    resources :employment_terms
  end

  root 'divisions#index'
end

app/models/division.rb
class Division < ApplicationRecord
  validates :name, presence: true
  
  has_many :employment_terms
  has_many :divisions, class_name: "Division", foreign_key: "parent_id", dependent: :destroy
  belongs_to :parent, class_name: "Division", optional: true
  acts_as_tree order: "name"
  
  def tree_as_json
    users = current_users
    divisions = {name: name, users: users, children: children.map { |child| child.tree_as_json }}
  
    divisions.as_json
  end
  
  def current_users
    current_employment_terms = employment_terms.where(end_date: nil)
    users = []
    current_employment_terms.each do |employment_term|
      user = "#{employment_term.user.l_name} #{employment_term.user.f_name} #{employment_term.user.s_name} - #{employment_term.position.position_history.name}"
      users << user
    end
  
    users.sort
  end

  # def tree_as_json
  #   divisions = {name: name, children: children.map { |child| child.tree_as_json }}

  #   divisions.as_json
  # end

  # def self.tree_as_json
  #   divisions ||= {}
  #   all_divisions = self.all

  #   all_divisions.each do |division|
  #     divisions[division.id] = {name: division.name, children: division.children.tree_as_json }
  #   end

  #   divisions.as_json
  # end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  def index
    # @divisions = Division.includes(employment_terms: [:user, position: [:position_history]]).where(employment_terms: {end_date: nil})
    divisions = Division.includes(employment_terms: [:user, position: [:position_history]])
    
    root = divisions.root

    @divisions_for_render = root.tree_as_json
  end

  def show
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/index.html.erb
<h1>Cтруктура подразделений предприятия</h1>

<%= @divisions_for_render %>

  <%# <table class="table table-striped">
    <thead>
      <tr>
        <th>Подразделение</th>
        <th>Количество сотрудников действующих</th>
      </tr>
    </thead>

    <tbody>
      <% @divisions.each do |division| %>
        <tr>
          <td><%#= division.name %></td>
          <td><%#= division.employment_terms.count %></td>
        </tr>
      <%# end %>
    </tbody>
  </table> %>

<%= link_to 'Все доступные должности', positions_path %> |
<%= link_to 'Все сотрудники', users_path %>

app/views/divisions/show.html.erb
<h1>Divisions#show</h1>
<p>Find me in app/views/divisions/show.html.erb</p>